### ISSUE TITLE
Regression in 1.3.10 in py3 for literal()

### ISSUE THREAD

**Issue by saaj** [PyMySQL/mysqlclient-python#174] opened 2017-05-28 10:49 UTC
# py2, py3, mysqlclient < 1.3.10 and py2, mysqlclient == 1.3.10 and pymysql (with proper import)
```
>>> import MySQLdb as mysql
>>> c = mysql.connect(user='guest')
>>> c.literal((1,2,3))
'(1,2,3)'
>>> c.literal(('1','2','3'))
"('1','2','3')"
```

# py3, mysqlclient == 1.3.10
```
>>> import MySQLdb as mysql
>>> c = mysql.connect(user='guest')
>>> c.literal((1,2,3))
'(1,2,3)'
>>> c.literal(('1','2','3'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 316, in literal
    s = self.escape(o, self.encoders)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/converters.py", line 90, in quote_tuple
    return "(%s)" % (','.join(escape_sequence(t, d)))
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by methane** [comment] 2017-05-28 12:25
This is duplicate of #145.
Read [this comment](https://github.com/PyMySQL/mysqlclient-python/issues/145#issuecomment-283936456).

Could you try #145?

**Closed** 2017-09-01 16:39 UTC
