### ISSUE TITLE
Binary wheel for Python 3.8

### ISSUE THREAD

**Issue by AndreyMZ** [PyMySQL/mysqlclient-python#391] opened 2019-10-24 10:22 UTC
## Problem description
There is no binary wheel for CPython 3.8 on PyPI: <https://pypi.org/project/mysqlclient/#files>.

## Steps to reproduce
~~~
docker run -it python:3.8 /usr/local/bin/pip install mysqlclient --only-binary=mysqlclient
~~~
### Actual result
~~~
# docker run -it python:3.8 /usr/local/bin/pip install mysqlclient --only-binary=mysqlclient
ERROR: Could not find a version that satisfies the requirement mysqlclient (from versions: none)
ERROR: No matching distribution found for mysqlclient
~~~
### Expected result
No errors.

**Comment by methane** [comment] 2019-10-24 10:35
Duplicate of #190.

**Closed by methane** 2019-10-24 10:35 UTC
