### ISSUE TITLE
undefined symbol: OPENSSL_add_all_algorithms_noconf

### ISSUE THREAD

**Issue by elraro** [PyMySQL/mysqlclient-python#184] opened 2017-06-19 21:59 UTC
First, sorry if this is not a mysqlclient problem.

- Debian 9.
- MariaDB 10.2
- mysqlclient last version, from pip

```
Traceback (most recent call last):
  File "dealsnotify.py", line 1, in <module>
    import utility
  File "/home/ofertas-bot-mv/utility.py", line 9, in <module>
    import MySQLdb
  File "/root/.virtualenvs/ofertas-mv/lib/python3.5/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: /root/.virtualenvs/ofertas-mv/lib/python3.5/site-packages/_mysql.cpython-35m-x86_64-linux-gnu.so: undefined symbol: OPENSSL_add_all_algorithms_noconf

ld _mysql.cpython-35m-x86_64-linux-gnu.so 
ld: warning: cannot find entry symbol _start; not setting start address
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyExc_ImportError'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyDict_SetItemString'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyType_GenericNew'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyExc_ValueError'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyType_Ready'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyLong_FromUnsignedLongLong'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyMem_Free'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `OPENSSL_add_all_algorithms_noconf'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_FromString'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `_PyTuple_Resize'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyErr_NoMemory'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyObject_GC_UnTrack'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `SSL_load_error_strings'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyExc_TypeError'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyDict_Type'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyExc_KeyError'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyObject_Str'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyObject_GetItem'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyModule_Type'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyDict_Next'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyLong_AsLong'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyArg_ParseTuple'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyErr_ExceptionMatches'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyErr_Occurred'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyObject_GenericSetAttr'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyMapping_Check'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyArg_ParseTupleAndKeywords'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `ERR_free_strings'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `_Py_FalseStruct'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyErr_SetObject'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyEval_RestoreThread'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyBytes_AsString'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_Type'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyObject_Size'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `EVP_cleanup'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `_Py_TrueStruct'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_AsASCIIString'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyEval_SaveThread'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyModule_GetDict'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PySequence_GetItem'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `_PyBytes_Resize'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyObject_GenericGetAttr'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PySequence_Size'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyType_IsSubtype'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `SSLv23_client_method'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyObject_Type'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PySequence_Check'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `SSL_library_init'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `Py_BuildValue'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyRun_StringFlags'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyMapping_HasKeyString'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `_Py_NoneStruct'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyBytes_FromStringAndSize'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyDict_GetItemString'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyErr_Print'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyExc_AttributeError'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyLong_FromLong'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `CRYPTO_cleanup_all_ex_data'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyImport_ImportModule'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyMapping_GetItemString'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyErr_Clear'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyModule_Create2'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyTuple_New'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyMapping_SetItemString'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyErr_SetString'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyObject_CallFunction'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_FromStringAndSize'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyType_GenericAlloc'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyMem_Malloc'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_AsUTF8'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyDict_SetItem'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `SSLv23_server_method'
_mysql.cpython-35m-x86_64-linux-gnu.so: undefined reference to `PyDict_New'
```

I dont know if is MariaDB 10.2 problem or mysqlclient

**Comment by methane** [comment] 2017-06-20 02:16
It's clearly your environment issue.
You failed to dynamic link to ssl, libpython and even glibc!

I don't know this is an issue of only your environment or common for Debian 9.

**Comment by elraro** [comment] 2017-06-20 06:17
Ok, thanks! I will try again with a VM Debian 9

**Comment by methane** [comment] 2017-06-20 07:22
I succeeded clean install on Debian 9.
I suppose you fall into common trap.

Maybe, your machine is upgraded from Debian 8?
If so, `rm -rf ~/.cache/pip` to remove all extensions build on Debian 8.

**Comment by elraro** [comment] 2017-06-20 08:27
Hi methane.

Yes, is a upgrade from Debian 8. Purged `~/.virtualenvs/`, `~/.cache/pip` and same error :(

Thanks for your help.

**Comment by elraro** [comment] 2017-06-21 10:39
`pip install --upgrade -I mysqlclient
Collecting mysqlclient
  Downloading mysqlclient-1.3.10.tar.gz (82kB)
    100% |████████████████████████████████| 92kB 3.3MB/s 
Building wheels for collected packages: mysqlclient
  Running setup.py bdist_wheel for mysqlclient ... error
  Complete output from command /root/.virtualenvs/ofertas-mv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-e36onr2y/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp_8khs737pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  copying _mysql_exceptions.py -> build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/MySQLdb
  copying MySQLdb/__init__.py -> build/lib.linux-x86_64-3.5/MySQLdb
  copying MySQLdb/compat.py -> build/lib.linux-x86_64-3.5/MySQLdb
  copying MySQLdb/connections.py -> build/lib.linux-x86_64-3.5/MySQLdb
  copying MySQLdb/converters.py -> build/lib.linux-x86_64-3.5/MySQLdb
  copying MySQLdb/cursors.py -> build/lib.linux-x86_64-3.5/MySQLdb
  copying MySQLdb/release.py -> build/lib.linux-x86_64-3.5/MySQLdb
  copying MySQLdb/times.py -> build/lib.linux-x86_64-3.5/MySQLdb
  creating build/lib.linux-x86_64-3.5/MySQLdb/constants
  copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
  copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
  copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
  copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
  copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
  copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
  copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
  running build_ext
  building '_mysql' extension
  creating build/temp.linux-x86_64-3.5
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-MLq5fN/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Dversion_info=(1,3,10,'final',0) -D__version__=1.3.10 -I/usr/include/mysql -I/usr/include/python3.5m -I/root/.virtualenvs/ofertas-mv/include/python3.5m -c _mysql.c -o build/temp.linux-x86_64-3.5/_mysql.o
  In file included from _mysql.c:30:0:
  /usr/include/mysql/mysql.h:438:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     MYSQL_CLIENT_PLUGIN_HEADER
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/include/mysql/mysql.h:583:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   my_bool STDCALL mysql_embedded();
   ^~~~~~~
  _mysql.c: In function ‘_mysql_ConnectionObject_ping’:
  _mysql.c:1911:41: error: ‘MYSQL {aka struct st_mysql}’ has no member named ‘reconnect’
    if ( reconnect != -1 ) self->connection.reconnect = reconnect;
                                           ^
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for mysqlclient
  Running setup.py clean for mysqlclient
Failed to build mysqlclient
Installing collected packages: mysqlclient
  Running setup.py install for mysqlclient ... error
    Complete output from command /root/.virtualenvs/ofertas-mv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-e36onr2y/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-me0xtyd0-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.virtualenvs/ofertas-mv/include/site/python3.5/mysqlclient:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    copying _mysql_exceptions.py -> build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/MySQLdb
    copying MySQLdb/__init__.py -> build/lib.linux-x86_64-3.5/MySQLdb
    copying MySQLdb/compat.py -> build/lib.linux-x86_64-3.5/MySQLdb
    copying MySQLdb/connections.py -> build/lib.linux-x86_64-3.5/MySQLdb
    copying MySQLdb/converters.py -> build/lib.linux-x86_64-3.5/MySQLdb
    copying MySQLdb/cursors.py -> build/lib.linux-x86_64-3.5/MySQLdb
    copying MySQLdb/release.py -> build/lib.linux-x86_64-3.5/MySQLdb
    copying MySQLdb/times.py -> build/lib.linux-x86_64-3.5/MySQLdb
    creating build/lib.linux-x86_64-3.5/MySQLdb/constants
    copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
    copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
    copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
    copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
    copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
    copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
    copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-3.5/MySQLdb/constants
    running build_ext
    building '_mysql' extension
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-MLq5fN/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Dversion_info=(1,3,10,'final',0) -D__version__=1.3.10 -I/usr/include/mysql -I/usr/include/python3.5m -I/root/.virtualenvs/ofertas-mv/include/python3.5m -c _mysql.c -o build/temp.linux-x86_64-3.5/_mysql.o
    In file included from _mysql.c:30:0:
    /usr/include/mysql/mysql.h:438:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
       MYSQL_CLIENT_PLUGIN_HEADER
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/mysql/mysql.h:583:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     my_bool STDCALL mysql_embedded();
     ^~~~~~~
    _mysql.c: In function ‘_mysql_ConnectionObject_ping’:
    _mysql.c:1911:41: error: ‘MYSQL {aka struct st_mysql}’ has no member named ‘reconnect’
      if ( reconnect != -1 ) self->connection.reconnect = reconnect;
                                             ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/root/.virtualenvs/ofertas-mv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-e36onr2y/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-me0xtyd0-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.virtualenvs/ofertas-mv/include/site/python3.5/mysqlclient" failed with error code 1 in /tmp/pip-build-e36onr2y/mysqlclient/`

**Comment by methane** [comment] 2017-06-21 10:41
It's not same error.  It's build error.
And it's duplicate of #176.

**Closed by methane** 2017-06-21 10:41 UTC

**Comment by elraro** [comment] 2017-06-21 11:19
Yes, was that. Thanks for your help and sorry.

**Comment by elraro** [comment] 2017-06-21 11:31
Ok, so the problem was use the mysqlclient from pip with mariadb 10.2.
