### ISSUE TITLE
Regression in bulk insert behavior

### ISSUE THREAD

**Issue by ajm188** [PyMySQL/mysqlclient-python#163] opened 2017-04-17 17:51 UTC
The following query _should_ be able to be executed in bulk:

```sql
INSERT INTO users (id, name) VALUES (1, 'foo'), (2, 'bar') /* insert multiple users in one query */
```

With mysqlclient 1.3.6, this query is emitted as a bulk insert.

I upgraded mysqclient to 1.3.9, and suddenly, this query is emitted as two individual inserts.

**Comment by ajm188** [comment] 2017-04-17 17:54
A `git bisect` shows [49e401b](https://github.com/PyMySQL/mysqlclient-python/commit/49e401b3bc2c123b36949baeb409b91dcbdf85a6) to be the commit that introduced this regression

**Comment by asottile** [comment] 2017-04-19 21:55
@methane  should we revert that commit? This is a pretty bad regression preventing us from upgrading

**Comment by methane** [comment] 2017-04-20 01:41
Why can't you just remove comment?

**Comment by asottile** [comment] 2017-04-20 01:44
We use comments to uniquely identify queries such that it can be known from the server where the (problematic) query came from.  It's incredibly useful for detecting "where did this come from and who and why and how can we stop it".

Comments **are** valid sql, refusing to support them seems not the best idea.

**Comment by methane** [comment] 2017-04-20 02:18
executemany() don't refuse it.
It just use normal execute().

**Comment by asottile** [comment] 2017-04-20 02:24
Correct it doesn't refuse it, but it turns a bulk insert (1.3.8) which was a single _fast_ query into thousands (millions even!).  This kills the db server.

**Comment by methane** [comment] 2017-04-20 02:28
execute() sends the query to MySQL.  It should support all valid SQL as possible.
On the other hand, executemany() try to **rebuild** SQL.  It can't support all valid SQL unless having full parser.
It must not break SQL.  It should fallback to execute() if it can be false positive.

**Comment by asottile** [comment] 2017-04-20 02:31
understood.  This *used* to work but was _broken_ in a patch release.  This works correctly with `mysql-python` also.  It's pretty simple to fix as well (as the two related pull requests demonstrate) -- I'm unsure why you are so adamant on not accepting a simple fix to a pretty clear regression.

**Comment by methane** [comment] 2017-04-20 02:44
Because it may cause false positive and break query.

**Comment by asottile** [comment] 2017-04-20 02:45
You already break query (this issue)!

If there's a demonstrated test with the fix will you accept a small pull request?

**Comment by asottile** [comment] 2017-04-20 02:53
This is an almost identical (in idea) PR which was accepted: https://github.com/PyMySQL/mysqlclient-python/pull/154

Why the difference of opinion here?

**Comment by methane** [comment] 2017-04-20 11:36
Because I don't think `;?\s*` can cause false positive.

**Comment by methane** [comment] 2017-04-20 11:55
#161 may have false positive. While I didn't test it, I feel it can match entire `/* xxx */ ON DUPLICATE KEY x=x+1 /* zzz */`

#162 may have false positive too.  `INSERT INTO x (a, b) values (%s, %s); INSERT INTO y (c, d) values (%s, %s);`

Most problem is maintenance cost.  Both of PyMySQL and MySQL-python had been unmaintained for years.  And I'm not active enough too.
I think focusing low level, simplicity, stability and performance is very important for project continuity.

Regular expression is one of part which makes project  maintenance difficult.
I don't want to pay my time to review complex regular expression which may cause false positive.
But `:?\s*` looks OK to me because it is short and it doesn't use `.*` or other dangerous expression which may cause false positive.

You can override cursor and implement your own executemany().
Or you can move your comment to other place like `INSERT INTO table /* comment here */ (c1, c2) values (%s, %s)`.

**Comment by asottile** [comment] 2017-04-20 14:51
If I craft a regular expression which provably cannot match nested comments would you accept a pull request?

**Comment by asottile** [comment] 2017-04-20 14:53
It's also bad practice on github to outright **close** pull requests without suggesting improvements.   I understand you don't want to maintain this project but that doesn't mean we have to be rude to each other :)

**Comment by asottile** [comment] 2017-04-20 15:21
Here's a regex which does not match too much:

```
/\*.*?\*/
```

I'll make a PR with this instead

**Comment by asottile** [comment] 2017-04-20 15:56
Err sorry, need a  little bit more complicated (but still pretty readable):

`/\*(?:[^*]|(?:\*+([^*/])))*\*+/`

1. start with `/*`
2. any number of these:
    - any number of non `*` characters
    - any number of `*` *not* followed by a `/`

**Comment by ajm188** [comment] 2017-04-20 16:01
For what it's worth, we can use `re.X` (aliased to `re.VERBOSE`) which would allow us to add comments to different parts of the regular expression. This would help add clarity to what is already (in my opinion) a very complex regex. [docs here](https://docs.python.org/2/library/re.html#re.X)

**Comment by methane** [comment] 2017-04-21 09:19
> If I craft a regular expression which provably cannot match nested comments would you accept a pull request?

If it's:

* obvious, easy to maintain, everyone can read and understand completely.
* zero false positive.

**Comment by methane** [comment] 2017-04-21 09:21
> It's also bad practice on github to outright close pull requests without suggesting improvements. I understand you don't want to maintain this project but that doesn't mean we have to be rude to each other :)

I don't have any idea improving such pull request.
And opening pull requests which doesn't have chance to merge make hard to maintain project.

**Comment by methane** [comment] 2017-04-21 09:23
> Err sorry, need a little bit more complicated (but still pretty readable):

Easy to understand is very important.

Current regex is cleary don't support last comment.
Your suggestion is unclear what type of comment is accepted.

**Comment by methane** [comment] 2017-04-21 09:33
`executemany()` is very special feature.  The API is not designed for SQL rewriting.
(DB-API 2.0 is not written only for MySQL)

So I think **user** should adjust their SQL to match the regular expression.
So the regular expression should be very easy to everyone who use `.executemany()`.

My plan is make the regex more strict, zero false positive.
And implement another fallback which is efficient than multiple `.execute()` call.
So I won't accept any complex regex which doesn't reduce false positive.

**Comment by methane** [comment] 2017-04-21 09:44
Additionally, I'm making difference between PyMySQL and mysqlclient smaller.
This is important to reduce maintenance cost too.

Since this project is GPL, please send pull request to PyMySQL.

**Comment by asottile** [comment] 2017-04-27 15:19
I've updated #165 and opened https://github.com/PyMySQL/PyMySQL/pull/566

**Comment by methane** [comment] 2017-04-27 15:27
I saw it.  But I dislike such complex regex only for trailing comment.  I don't want merge it.

I have more safer idea about `executemany()`.  Something like:

```
batched_query = ";\n".join(self.mogrify(query, p)) for p in params)
return self.execute(batched_query)
```

But I don't have time to verify the idea.  Especially, I want to know how
performance worce.  3x is acceptable but 30x is not acceptable.

If you really want trailing comma support, could you try it?

**Comment by asottile** [comment] 2017-04-27 16:48
The regex is dead simple (much _much_ simpler than the parentheses one right above it!), it looks more complicated because of the non capturing groups.  Without them it is much more readable:

```
/\*([^*]|(\*+([^*/])))*\*+/
```

**Comment by ajm188** [comment] 2017-04-29 11:52
@methane trailing comment is becoming quite a common pattern in SQL querying, **specifically** for the purposes of annotating where in source code a query came from.

For example, [here is a ruby gem](https://github.com/basecamp/marginalia#marginalia-) whose sole feature is to add these sorts of annotations to queries. It's developed and maintained by basecamp (owned by Rails creator DHH), and they've been [using it in production since 2012](https://signalvnoise.com/posts/3130-tech-note-mysql-query-comments-in-rails). Notably,

> When we’re trying to improve a slow query, or identify a customer problem, we never have to go digging to understand where the query came from—it’s just right there. This comes in handy in development, support, and operations .... If you combine this with something like pt-query-digest, you end up with a powerful understanding of how each Rails action interacts with MySQL.

Supporting query annotations (via comments) seems perfectly valid to me, and there's plenty of prior art for supporting this in other ORMs.

**Comment by methane** [comment] 2017-04-29 12:14
In general, yes.  But executemany() is very special purpose method.
Please fork and maintenance it by yourself.

**Comment by ajm188** [comment] 2017-04-29 16:37
Can you explain to me how executemany() is "very special purpose"?

I genuinely don't feel like it needs to be.

**Comment by methane** [comment] 2017-04-29 16:51
execute() is general, executemany() is special.  Is there any question about that???
I don't have enough English skill to answer such type of question.

**Comment by methane** [comment] 2017-04-29 17:10
If I accept this, why not heading comment?  comment between `INSERT` and opening `(`?
comments between values?

`executmany()` builds "bulk insert" query from template.
Fundamentally, this is not job of driver.  It's job of ORM or other SQL utilities.

My design is queries matching simple pattern are convert to "bulk insert" query.
And I plan to implement fallback using multi statement.  When I (or some other
volunteer) implement it, this issue will be fixed.

But **keeping the pattern minimum is my design decision.**
There are no chance to accept pull request making the pattern complicated.

Instead, you can make your library for building query.

I have no time and energy to talk about this issue anymore.

**Closed by methane** 2017-04-29 17:10 UTC

**Comment by ajm188** [comment] 2017-04-29 19:57
Your argument is a tautology. "executemany is special because it is special"

> If I accept this why not heading comment? comment between `INSERT` and opening `(`? comments  between values?

Yes!!! These are all valid SQL queries that can be executed in bulk!! Supporting these would be fantastic for users of your library. I am happy to help add support for these.

> **keeping the pattern minimum is my design decision**

I would agree with you, were it not for two points:
1. As @asottile has previously stated, the pattern is _already_ complicated.
1. The pattern is fundamentally **incorrect**, and can be shown to be broken with trivial examples.

**Comment by methane** [comment] 2017-04-30 00:59
> Your argument is a tautology. "executemany is special because it is special"

`execute()` executes SQL passed.  It driver's job and it support trailing comment.
On same point of view, `executemany()` **supports** trailing comment comment.
Driver don't know SQL.  It only knows escaping rule.

On the other hand, building "bulk insert" is not driver's job.  It needs knowledge of SQL.
It is implemented as just a bonus.  There are no guarantee like "all SQL are supported."

> Yes!!! These are all valid SQL queries that can be executed in bulk!! Supporting these would be fantastic for users of your library. I am happy to help add support for these.

I hate it!!  That's what I don't want to maintain!!!
You can create your own library to build SQL which I won't maintain.

> As @asottile has previously stated, the pattern is already complicated.

Current complicity is needed to avoid false positive.  Avoiding false positive is important to use
fallback safely.

> The pattern is fundamentally incorrect, and can be shown to be broken with trivial examples.

NO! It's not broken.  It just doesn't support all insert SQL.
It only support very limited pattern **by design, internationally**.

But I'm tired to talking with you.  I'm considering completely remove the feature.
I want to reduce maintenance cost, and this thread is very huge cost to me.
